/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './components/**/*.{vue,js,ts}',
    './layouts/**/*.vue',
    './pages/**/*.vue',
    './composables/**/*.{js,ts}',
    './plugins/**/*.{js,ts}',
    './app.vue',
    './error.vue',
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          DEFAULT: '#0f172a',
          accent: '#2b7a78',
          soft: '#e9f1f0',
        },
        // Premium Industrial Design System
        primary: '#000000',
        secondary: '#0060ac',
        tertiary: '#000000',
        surface: '#f8f9fa',
        error: '#ba1a1a',
        'on-primary': '#ffffff',
        'on-secondary': '#ffffff',
        'on-tertiary': '#ffffff',
        'on-surface': '#191c1d',
        'on-error': '#ffffff',
        'primary-container': '#0d1c32',
        'secondary-container': '#68abff',
        'tertiary-container': '#161d1f',
        'error-container': '#ffdad6',
        'on-primary-container': '#76849f',
        'on-secondary-container': '#003e73',
        'on-tertiary-container': '#7e8587',
        'on-error-container': '#93000a',
        'surface-bright': '#f8f9fa',
        'surface-dim': '#d9dadb',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f4f5',
        'surface-container': '#edeeef',
        'surface-container-high': '#e7e8e9',
        'surface-container-highest': '#e1e3e4',
        'surface-variant': '#e1e3e4',
        'on-surface-variant': '#44474d',
        outline: '#75777e',
        'outline-variant': '#c5c6cd',
        'inverse-surface': '#2e3132',
        'inverse-on-surface': '#f0f1f2',
        'inverse-primary': '#b9c7e4',
        'primary-fixed': '#d6e3ff',
        'primary-fixed-dim': '#b9c7e4',
        'secondary-fixed': '#d4e3ff',
        'secondary-fixed-dim': '#a4c9ff',
        'tertiary-fixed': '#dde4e6',
        'tertiary-fixed-dim': '#c1c8ca',
        'on-primary-fixed': '#0d1c32',
        'on-primary-fixed-variant': '#39475f',
        'on-secondary-fixed': '#001c39',
        'on-secondary-fixed-variant': '#004883',
        'on-tertiary-fixed': '#161d1f',
        'on-tertiary-fixed-variant': '#41484a',
        'surface-tint': '#515f78',
      },
      fontFamily: {
        sans: ['"Inter"', 'system-ui', 'sans-serif'],
        headline: ['"Manrope"', 'system-ui', 'sans-serif'],
        body: ['"Inter"', 'system-ui', 'sans-serif'],
        label: ['"Inter"', 'system-ui', 'sans-serif'],
      },
      container: {
        center: true,
        padding: '1.25rem',
      },
    },
  },
  plugins: [],
};
