<script setup lang="ts">
const { api, tr, errorText, statusLabel, date } = useLmsApi();
const { data: overview, pending, error, refresh } = await useAsyncData('lms-document-batch-source', () => api<any>('/admin/operations'));
const historyPage = ref(1);
const { data: history, refresh: refreshHistory } = await useAsyncData('lms-document-batches', () => api<any>('/admin/credential-batches', { query: { page: historyPage.value } }));
const action = ref('issue'); const selected = ref<string[]>([]); const reason = ref(''); const confirmed = ref(false);
const batch = ref<any>(null); const busy = ref(false); const failure = ref('');
watch(action, () => { selected.value = []; batch.value = null; confirmed.value = false; });
const targets = computed(() => action.value === 'issue'
  ? (overview.value?.enrollments || []).map((row: any) => ({ id: row.id, label: `${row.learnerName} · ${row.programId}`, detail: row.id }))
  : (overview.value?.credentials || []).filter((row: any) => ['pending', 'issued'].includes(row.status)).map((row: any) => ({ id: row.id, label: row.serial, detail: statusLabel(row.status) })));
const batchState = (value: string) => ({ preview: tr('Предварительный просмотр', 'Алдын ала қарау'), processing: tr('Есть необработанные записи', 'Өңделмеген жазбалар бар'), completed: tr('Операции выполнены', 'Операциялар орындалды'), partial: tr('Завершено с отклонёнными записями', 'Қабылданбаған жазбалармен аяқталды') }[value] || value);
async function preview() { busy.value = true; failure.value = ''; confirmed.value = false; try { batch.value = await api('/admin/credential-batches', { method: 'POST', body: { action: action.value, targetIds: selected.value, reason: reason.value } }); await refreshHistory(); } catch (cause) { failure.value = errorText(cause); } finally { busy.value = false; } }
async function open(id: string) { busy.value = true; failure.value = ''; confirmed.value = false; try { batch.value = await api(`/admin/credential-batches/${encodeURIComponent(id)}`); } catch (cause) { failure.value = errorText(cause); } finally { busy.value = false; } }
async function commit() { if (!batch.value || !confirmed.value) return; busy.value = true; failure.value = ''; try { batch.value = await api(`/admin/credential-batches/${encodeURIComponent(batch.value.id)}/commit`, { method: 'POST', body: { confirmed: true } }); confirmed.value = false; await Promise.all([refresh(), refreshHistory()]); } catch (cause) { failure.value = errorText(cause); } finally { busy.value = false; } }
async function turn(delta: number) { historyPage.value += delta; await refreshHistory(); }
useHead(() => ({ title: tr('Пакетные операции документов — OT Center', 'Құжаттардың топтық операциялары — OT Center'), meta: [{ name: 'robots', content: 'noindex, nofollow' }] }));
</script>
<template>
  <LmsShell :title="tr('Пакетные операции документов', 'Құжаттардың топтық операциялары')" back="/admin">
    <p class="text-slate-600">{{ tr('Выберите до 10 записей и проверьте предварительный результат. Подтверждение оформления создаёт очередь подготовки PDF. Готовность документа проверяется отдельно; результат по каждой записи сохраняется.', '10 жазбаға дейін таңдап, алдын ала нәтижені тексеріңіз. Рәсімдеуді растау PDF дайындау кезегін жасайды. Құжаттың дайындығы бөлек тексеріледі; әр жазбаның нәтижесі сақталады.') }}</p>
    <LmsState :pending="pending" :error="error" @retry="refresh()">
      <form class="lms-card space-y-5" @submit.prevent="preview()">
        <label class="block space-y-2"><span>{{ tr('Операция', 'Операция') }}</span><select v-model="action"><option value="issue">{{ tr('Подготовить документы', 'Құжаттарды дайындау') }}</option><option value="revoke">{{ tr('Отозвать документы', 'Құжаттарды кері қайтару') }}</option></select></label>
        <fieldset class="space-y-3"><legend class="font-semibold">{{ tr('Записи из последних 100 назначений / документов', 'Соңғы 100 тағайындау / құжат ішіндегі жазбалар') }}</legend><p v-if="!targets.length">{{ tr('Доступных записей пока нет.', 'Әзірге қолжетімді жазбалар жоқ.') }}</p><label v-for="target in targets" :key="target.id" class="flex items-start gap-3 rounded-lg border border-slate-200 p-3"><input v-model="selected" type="checkbox" :value="target.id" :disabled="!selected.includes(target.id) && selected.length >= 10" class="mt-1" /><span class="min-w-0"><span class="block font-semibold">{{ target.label }}</span><span class="break-all text-sm text-slate-600">{{ target.detail }}</span></span></label></fieldset>
        <p class="text-sm">{{ tr('Выбрано', 'Таңдалды') }}: {{ selected.length }} / 10</p>
        <label class="block space-y-2"><span>{{ tr('Основание операции для выбранных записей', 'Таңдалған жазбалар үшін операция негізі') }}</span><textarea v-model="reason" required minlength="10" maxlength="2000" /></label>
        <button class="lms-button" :disabled="busy || !selected.length">{{ tr('Проверить и показать результат', 'Тексеріп, нәтижені көрсету') }}</button>
      </form>
    </LmsState>
    <section v-if="batch" class="lms-card space-y-4" aria-live="polite"><h2 class="text-2xl font-bold">{{ batchState(batch.status) }}</h2><p>{{ batch.action === 'issue' ? tr('Подготовка документов', 'Құжаттарды дайындау') : tr('Отзыв документов', 'Құжаттарды кері қайтару') }}</p><p class="whitespace-pre-wrap">{{ batch.reason }}</p><p class="text-sm">{{ tr('Первое подтверждение доступно до', 'Алғашқы растау қолжетімді мерзім') }}: {{ date(batch.expiresAt) }}</p>
      <ul class="space-y-3"><li v-for="item in batch.items" :key="item.targetId" class="rounded-lg border border-slate-200 p-4"><p class="font-semibold">{{ item.preview.learnerName || item.targetId }} · {{ item.preview.programTitle || item.preview.serial || '' }}</p><p v-if="item.preview.templateName" class="text-sm">{{ tr('Утверждённый бланк', 'Бекітілген бланк') }}: {{ item.preview.templateName }}</p><p v-if="item.status === 'failed'" class="lms-error">{{ errorText({ data: { code: item.errorCode }, statusCode: 409 }) }} <span class="text-xs">({{ item.errorCode }})</span></p><p v-else-if="item.status === 'completed'">{{ item.result?.credential ? tr('Документ зарегистрирован. Состояние подготовки PDF', 'Құжат тіркелді. PDF дайындау күйі') + ': ' + statusLabel(item.result.credential.status) + ' · ' + item.result.credential.serial : tr('Документ отозван.', 'Құжат кері қайтарылды.') }}</p><p v-else>{{ tr('Ожидает подтверждения или продолжения обработки.', 'Растауды немесе өңдеуді жалғастыруды күтуде.') }}</p></li></ul>
      <form v-if="['preview', 'processing'].includes(batch.status) && batch.items.some((item: any) => item.status === 'pending')" class="space-y-4" @submit.prevent="commit()"><label class="flex items-start gap-3"><input v-model="confirmed" type="checkbox" required class="mt-1" /><span>{{ tr('Проверил состав, основание и доступные записи. Подтверждаю указанную операцию.', 'Құрамын, негізін және қолжетімді жазбаларды тексердім. Көрсетілген операцияны растаймын.') }}</span></label><button class="lms-button" :disabled="busy || !confirmed">{{ tr('Подтвердить обработку', 'Өңдеуді растау') }}</button></form>
      <button class="lms-button secondary" :disabled="busy" @click="open(batch.id)">{{ tr('Обновить состояние пакета', 'Топ күйін жаңарту') }}</button>
    </section>
    <p v-if="failure" class="lms-error" role="alert">{{ failure }}</p>
    <section v-if="history" class="lms-card space-y-4"><h2 class="text-2xl font-bold">{{ tr('История операций', 'Операциялар тарихы') }}</h2><p>{{ tr('Всего', 'Барлығы') }}: {{ history.pagination.total }}</p><ul class="space-y-3"><li v-for="item in history.batches" :key="item.id"><button class="text-left underline" :disabled="busy" @click="open(item.id)">{{ date(item.createdAt) }} · {{ item.action === 'issue' ? tr('Оформление', 'Рәсімдеу') : tr('Отзыв', 'Кері қайтару') }} · {{ batchState(item.status) }}</button></li></ul><div class="flex flex-wrap gap-3"><button class="lms-button secondary" :disabled="historyPage <= 1" @click="turn(-1)">{{ tr('Предыдущая страница', 'Алдыңғы бет') }}</button><button class="lms-button secondary" :disabled="!history.pagination.hasMore" @click="turn(1)">{{ tr('Следующая страница', 'Келесі бет') }}</button></div></section>
  </LmsShell>
</template>
