<script setup lang="ts">
const { api, tr, date, errorText } = useLmsApi();
const search = ref(''); const users = ref<any[]>([]); const user = ref<any>(null); const notes = ref<any>(null); const page = ref(1);
const text = ref(''); const supersedesId = ref<string | null>(null); const busy = ref(false); const failure = ref(''); const success = ref('');
async function find() { busy.value = true; failure.value = ''; try { users.value = (await api<any>('/admin/users', { query: { query: search.value } })).users; } catch (cause) { failure.value = errorText(cause); } finally { busy.value = false; } }
async function load() { if (user.value) notes.value = await api(`/admin/support-notes/${encodeURIComponent(user.value.id)}`, { query: { page: page.value } }); }
async function choose(value: any) { busy.value = true; failure.value = ''; success.value = ''; user.value = value; notes.value = null; text.value = ''; supersedesId.value = null; page.value = 1; try { await load(); } catch (cause) { failure.value = errorText(cause); } finally { busy.value = false; } }
async function turn(delta: number) { busy.value = true; page.value += delta; try { await load(); } catch (cause) { failure.value = errorText(cause); } finally { busy.value = false; } }
async function save() { if (!user.value) return; busy.value = true; failure.value = ''; success.value = ''; try { await api(`/admin/support-notes/${encodeURIComponent(user.value.id)}`, { method: 'POST', body: { text: text.value, supersedesId: supersedesId.value } }); text.value = ''; supersedesId.value = null; page.value = 1; await load(); success.value = tr('Заметка сохранена в истории поддержки.', 'Ескерту қолдау тарихына сақталды.'); } catch (cause) { failure.value = errorText(cause); } finally { busy.value = false; } }
useHead(() => ({ title: tr('Поддержка слушателей — OT Center', 'Тыңдаушыларды қолдау — OT Center'), meta: [{ name: 'robots', content: 'noindex, nofollow' }] }));
</script>
<template>
  <LmsShell :title="tr('Поддержка слушателей', 'Тыңдаушыларды қолдау')" back="/admin">
    <form class="lms-card flex flex-wrap items-end gap-4" @submit.prevent="find()"><label class="flex-1 space-y-2"><span>{{ tr('Имя или email пользователя', 'Пайдаланушының аты немесе email') }}</span><input v-model="search" type="search" required minlength="2" maxlength="150" /></label><button class="lms-button" :disabled="busy">{{ tr('Найти пользователя', 'Пайдаланушыны табу') }}</button></form>
    <ul class="grid gap-3 md:grid-cols-2"><li v-for="person in users" :key="person.id" class="lms-card space-y-3"><p class="font-semibold">{{ person.name }}</p><p class="break-all text-sm">{{ person.email }}</p><button class="lms-button secondary" :disabled="busy" @click="choose(person)">{{ tr('Открыть историю поддержки', 'Қолдау тарихын ашу') }}</button></li></ul>
    <section v-if="user && notes" class="space-y-5"><h2 class="text-2xl font-bold">{{ user.name }}</h2><p>{{ tr('Заметок в истории', 'Тарихтағы ескертулер') }}: {{ notes.pagination.total }}</p><ul class="space-y-3"><li v-for="note in notes.notes" :key="note.id" class="lms-card space-y-3"><p class="whitespace-pre-wrap">{{ note.body }}</p><p class="text-sm text-slate-600">{{ note.authorName }} · {{ date(note.createdAt) }}</p><p v-if="note.supersedesId" class="break-all text-sm">{{ tr('Уточняет запись', 'Жазбаны нақтылайды') }}: {{ note.supersedesId }}</p><button class="lms-button secondary" :disabled="busy" @click="supersedesId = note.id; text = ''">{{ tr('Добавить уточнение', 'Нақтылау қосу') }}</button></li></ul><div class="flex flex-wrap gap-3"><button class="lms-button secondary" :disabled="busy || page <= 1" @click="turn(-1)">{{ tr('Предыдущая страница', 'Алдыңғы бет') }}</button><button class="lms-button secondary" :disabled="busy || !notes.pagination.hasMore" @click="turn(1)">{{ tr('Следующая страница', 'Келесі бет') }}</button></div>
      <form class="lms-card space-y-4" @submit.prevent="save()"><label class="block space-y-2"><span>{{ supersedesId ? tr('Уточнение к выбранной записи', 'Таңдалған жазбаға нақтылау') : tr('Новая заметка', 'Жаңа ескерту') }}</span><textarea v-model="text" required minlength="10" maxlength="2000" /></label><p class="text-sm text-slate-600">{{ tr('Фиксируйте вопрос и выполненные действия. Не добавляйте пароли, банковские данные или избыточные персональные сведения. Уточнение сохраняет исходную запись.', 'Сұрақ пен орындалған әрекеттерді жазыңыз. Құпиясөздерді, банк деректерін немесе артық жеке мәліметтерді қоспаңыз. Нақтылау бастапқы жазбаны сақтайды.') }}</p><div class="flex flex-wrap gap-3"><button class="lms-button" :disabled="busy">{{ tr('Сохранить заметку', 'Ескертуді сақтау') }}</button><button v-if="supersedesId" type="button" class="lms-button secondary" @click="supersedesId = null">{{ tr('Отменить уточнение', 'Нақтылаудан бас тарту') }}</button></div></form>
    </section>
    <p v-if="failure" class="lms-error" role="alert">{{ failure }}</p><p v-if="success" class="lms-success" role="status">{{ success }}</p>
  </LmsShell>
</template>
