export const cities = [
  {
    code: 'almaty',
    slug: 'almaty',
    nameRu: 'Алматы',
    nameRuPrepositional: 'в Алматы',
    nameKk: 'Алматы',
    nameKkPrepositional: 'Алматыда',
    phone: '+77755619871',
    address: 'г. Алматы, ул. Примерная, 1',
    email: 'otcenterkz@proton.me',
  },
  {
    code: 'astana',
    slug: 'astana',
    nameRu: 'Астана',
    nameRuPrepositional: 'в Астане',
    nameKk: 'Астана',
    nameKkPrepositional: 'Астанада',
  },
  {
    code: 'shymkent',
    slug: 'shymkent',
    nameRu: 'Шымкент',
    nameRuPrepositional: 'в Шымкенте',
    nameKk: 'Шымкент',
    nameKkPrepositional: 'Шымкентте',
  },
  {
    code: 'karaganda',
    slug: 'karaganda',
    nameRu: 'Караганда',
    nameRuPrepositional: 'в Караганде',
    nameKk: 'Қарағанды',
    nameKkPrepositional: 'Қарағандыда',
  },
  {
    code: 'atyrau',
    slug: 'atyrau',
    nameRu: 'Атырау',
    nameRuPrepositional: 'в Атырау',
    nameKk: 'Атырау',
    nameKkPrepositional: 'Атырауда',
  },
  {
    code: 'aktau',
    slug: 'aktau',
    nameRu: 'Актау',
    nameRuPrepositional: 'в Актау',
    nameKk: 'Ақтау',
    nameKkPrepositional: 'Ақтауда',
  },
  {
    code: 'pavlodar',
    slug: 'pavlodar',
    nameRu: 'Павлодар',
    nameRuPrepositional: 'в Павлодаре',
    nameKk: 'Павлодар',
    nameKkPrepositional: 'Павлодарда',
  },
  {
    code: 'ust-kamenogorsk',
    slug: 'ust-kamenogorsk',
    nameRu: 'Усть-Каменогорск',
    nameRuPrepositional: 'в Усть-Каменогорске',
    nameKk: 'Өскемен',
    nameKkPrepositional: 'Өскеменде',
  },
  {
    code: 'kostanay',
    slug: 'kostanay',
    nameRu: 'Костанай',
    nameRuPrepositional: 'в Костанае',
    nameKk: 'Қостанай',
    nameKkPrepositional: 'Қостанайда',
  },
  {
    code: 'taraz',
    slug: 'taraz',
    nameRu: 'Тараз',
    nameRuPrepositional: 'в Таразе',
    nameKk: 'Тараз',
    nameKkPrepositional: 'Таразда',
  },
  {
    code: 'kyzylorda',
    slug: 'kyzylorda',
    nameRu: 'Кызылорда',
    nameRuPrepositional: 'в Кызылорде',
    nameKk: 'Қызылорда',
    nameKkPrepositional: 'Қызылордада',
  },
  {
    code: 'aktobe',
    slug: 'aktobe',
    nameRu: 'Актобе',
    nameRuPrepositional: 'в Актобе',
    nameKk: 'Ақтөбе',
    nameKkPrepositional: 'Ақтөбеде',
  },
  {
    code: 'petropavlovsk',
    slug: 'petropavlovsk',
    nameRu: 'Петропавловск',
    nameRuPrepositional: 'в Петропавловске',
    nameKk: 'Петропавл',
    nameKkPrepositional: 'Петропавлда',
  },
  {
    code: 'semey',
    slug: 'semey',
    nameRu: 'Семей',
    nameRuPrepositional: 'в Семее',
    nameKk: 'Семей',
    nameKkPrepositional: 'Семейде',
  },
  {
    code: 'uralsk',
    slug: 'uralsk',
    nameRu: 'Уральск',
    nameRuPrepositional: 'в Уральске',
    nameKk: 'Орал',
    nameKkPrepositional: 'Оралда',
  },
];

export const defaultCitySlug = 'almaty';
