import { createCipheriv, createDecipheriv, randomBytes, scryptSync } from 'node:crypto';
import { readFile, writeFile, open } from 'node:fs/promises';
import { resolve } from 'node:path';
import { createClient, type Client } from '@libsql/client';
import { getDb, closeDb } from '../server/db';

const quote = (name: string) => `"${name.replaceAll('"', '""')}"`;
const encodeValue = (value: unknown): unknown => value instanceof ArrayBuffer ? { __ot_blob: Buffer.from(value).toString('base64') } : typeof value === 'bigint' ? { __ot_bigint: value.toString() } : value;
function decodeValue(value: any): any {
  if (value && typeof value === 'object') {
    if (Object.keys(value).length === 1 && typeof value.__ot_blob === 'string' && /^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/.test(value.__ot_blob)) return Buffer.from(value.__ot_blob, 'base64');
    if (Object.keys(value).length === 1 && typeof value.__ot_bigint === 'string' && /^-?\d+$/.test(value.__ot_bigint)) return BigInt(value.__ot_bigint);
    throw new Error('Invalid encoded database value');
  }
  if (value !== null && typeof value !== 'string' && (typeof value !== 'number' || !Number.isFinite(value))) throw new Error('Invalid database value');
  return value;
}
function validateSnapshot(backup: any) {
  if (!backup || backup.format !== 'ot-center-backup-v1' || !Array.isArray(backup.schema) || !Array.isArray(backup.tables)) throw new Error('Unsupported backup');
  const names = new Set<string>();
  for (const item of backup.schema) {
    if (!item || !['table', 'index', 'trigger', 'view'].includes(item.type) || typeof item.name !== 'string' || typeof item.sql !== 'string' || names.has(item.name)) throw new Error('Invalid backup schema');
    // Only schema statements generated by sqlite_master are admitted. Arbitrary ATTACH/PRAGMA/DML
    // from a malformed file must not execute with the restoring owner's filesystem permissions.
    const prefix = new RegExp(`^CREATE\\s+(?:UNIQUE\\s+)?${item.type}\\s`, 'i');
    if (!prefix.test(item.sql.trim())) throw new Error('Invalid backup schema statement');
    names.add(item.name);
  }
  const tableNames = new Set(backup.schema.filter((item: any) => item.type === 'table').map((item: any) => item.name));
  if (backup.tables.length !== tableNames.size) throw new Error('Backup table inventory mismatch');
  const seen = new Set();
  for (const table of backup.tables) {
    if (!table || !tableNames.has(table.name) || seen.has(table.name) || !Array.isArray(table.columns) || !table.columns.length || new Set(table.columns).size !== table.columns.length || table.columns.some((column: any) => typeof column !== 'string') || !Array.isArray(table.rows)) throw new Error('Invalid backup table');
    seen.add(table.name);
    for (const row of table.rows) {
      if (!Array.isArray(row) || row.length !== table.columns.length) throw new Error('Backup row width mismatch');
      for (const value of row) decodeValue(value);
    }
  }
}
export async function exportDatabase(db: Client) {
  const tx = await db.transaction('read');
  try {
    const schema = (await tx.execute("SELECT type,name,tbl_name,sql FROM sqlite_master WHERE sql IS NOT NULL AND name NOT LIKE 'sqlite_%' ORDER BY CASE type WHEN 'table' THEN 0 WHEN 'index' THEN 1 ELSE 2 END,name")).rows;
    const tables = [];
    for (const table of schema.filter(row => row.type === 'table')) {
      const result = await tx.execute(`SELECT * FROM ${quote(String(table.name))}`);
      tables.push({ name: String(table.name), columns: result.columns, rows: result.rows.map(row => Array.from(row).map(encodeValue)) });
    }
    await tx.commit();
    return { format: 'ot-center-backup-v1', createdAt: new Date().toISOString(), schema, tables };
  } catch (error) { if (!tx.closed) await tx.rollback(); throw error; } finally { tx.close(); }
}
export function encryptBackup(payload: unknown, password: string) {
  if (password.length < 24) throw new Error('Backup password must have at least 24 characters');
  const salt = randomBytes(16), iv = randomBytes(12), key = scryptSync(password, salt, 32);
  const cipher = createCipheriv('aes-256-gcm', key, iv);
  const data = Buffer.concat([cipher.update(JSON.stringify(payload), 'utf8'), cipher.final()]);
  return Buffer.concat([Buffer.from('OTB1'), salt, iv, cipher.getAuthTag(), data]);
}
export function decryptBackup(data: Buffer, password: string) {
  if (data.length < 49 || data.subarray(0, 4).toString() !== 'OTB1') throw new Error('Invalid backup format');
  const key = scryptSync(password, data.subarray(4, 20), 32);
  const decipher = createDecipheriv('aes-256-gcm', key, data.subarray(20, 32)); decipher.setAuthTag(data.subarray(32, 48));
  return JSON.parse(Buffer.concat([decipher.update(data.subarray(48)), decipher.final()]).toString('utf8'));
}
export async function restoreDatabase(db: Client, backup: any) {
  validateSnapshot(backup);
  const existing = (await db.execute("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'")).rows;
  if (existing.length) throw new Error('Restore target must be empty; no overwrite is allowed');
  await db.execute('PRAGMA foreign_keys=OFF');
  const tx = await db.transaction('write');
  try {
    for (const item of backup.schema.filter((item: any) => item.type === 'table')) await tx.execute(item.sql);
    for (const table of backup.tables) for (const row of table.rows) await tx.execute({ sql: `INSERT INTO ${quote(table.name)}(${table.columns.map(quote).join(',')}) VALUES(${table.columns.map(() => '?').join(',')})`, args: row.map(decodeValue) });
    for (const item of backup.schema.filter((item: any) => item.type !== 'table')) await tx.execute(item.sql);
    const integrity = await tx.execute('PRAGMA foreign_key_check'); if (integrity.rows.length) throw new Error('Backup violates foreign keys');
    const physicalIntegrity = await tx.execute('PRAGMA integrity_check'); if (physicalIntegrity.rows.some(row => row[0] !== 'ok')) throw new Error('Backup database integrity check failed');
    await tx.commit();
  } catch (error) { if (!tx.closed) await tx.rollback(); throw error; } finally { tx.close(); await db.execute('PRAGMA foreign_keys=ON'); }
}
if (process.argv[1]?.replaceAll('\\', '/').endsWith('/db-backup.ts')) {
  const [operation, filename, target] = process.argv.slice(2); const password = process.env.OT_BACKUP_PASSWORD || '';
  if (!filename || !['backup', 'restore'].includes(operation || '')) throw new Error('Usage: db-backup.ts backup <new-file> | restore <backup-file> <new-local-db>');
  if (operation === 'backup') {
    try { const snapshot = await exportDatabase(await getDb()); await writeFile(resolve(filename), encryptBackup(snapshot, password), { flag: 'wx', mode: 0o600 }); }
    finally { await closeDb(); }
  } else {
    if (!target) throw new Error('New local restore target is required');
    const snapshot = decryptBackup(await readFile(resolve(filename)), password); validateSnapshot(snapshot);
    const destination = resolve(target);
    // Exclusive creation removes the check-then-open race and never opens an existing target.
    const reservation = await open(destination, 'wx', 0o600); await reservation.close();
    const db = createClient({ url: `file:${destination.replaceAll('\\', '/')}`, concurrency: 1 });
    try { await restoreDatabase(db, snapshot); } finally { db.close(); }
  }
  console.log(JSON.stringify({ status: 'passed', operation }));
}
