<script setup lang="ts">
import type { SalesMetric, SalesReport, SalesStageId } from '~/shared/sales-report';
import type { JourneyContext } from '~/shared/lead-attribution';
import { leadCityLabel } from '~/shared/lead-context';
const props = defineProps<{ report: SalesReport }>();
const { tr, locale } = useLmsApi();
const path = useLocalePath();
const titles = computed<Record<SalesStageId, string>>(() => ({
  journeys: tr('Сессии вкладок с согласием', 'Келісім берілген қойынды сессиялары'),
  landing: tr('Посещение публичной страницы', 'Жария бетке кіру'),
  program: tr('Просмотр направления', 'Бағытты қарау'),
  consultation: tr('Переход к обращению', 'Өтінішке өту'),
  accepted: tr('Заявка принята', 'Өтінім қабылданды'),
  qualified: tr('Заявка квалифицирована сотрудником', 'Өтінімді қызметкер іріктеді'),
  sent: tr('Отправка предложения зафиксирована', 'Ұсынысты жіберу тіркелді'),
  organizationLinked: tr('Организация явно связана', 'Ұйым нақты байланыстырылды'),
  assigned: tr('Указаны конкретные назначения', 'Нақты тағайындаулар көрсетілді'),
  confirmedAccess: tr('Доступ к обучению подтверждён', 'Оқуға қолжетімділік расталды'),
  started: tr('Обучение начато', 'Оқу басталды'),
  requiredContent: tr('Обязательное содержание завершено', 'Міндетті мазмұн аяқталды'),
  assessmentPassed: tr('Проверка знаний пройдена', 'Білімді тексеруден өтті'),
  validCredential: tr('Действующий документ выдан', 'Қолданыстағы құжат берілді'),
}));
const funnels = computed(() => [
  { id: 'journey', title: tr('Путь вкладок с согласием', 'Келісім берілген қойындылар жолы'), unit: tr('Одна вкладка с явным согласием; это не уникальный человек.', 'Нақты келісімі бар бір қойынды; бұл бірегей адам емес.'), population: tr('Только записанные пути с согласием, срок хранения которых ещё не истёк на момент отчёта. Посещения до согласия и браузеры без согласия не входят в эту группу.', 'Тек келісіммен жазылған және есеп кезінде сақтау мерзімі аяқталмаған жолдар. Келісімге дейінгі кірулер мен келісімсіз браузерлер бұл топқа кірмейді.'), value: props.report.journeyOutcomes },
  { id: 'b2c', title: tr('От индивидуальной заявки к обучению', 'Жеке өтінімнен оқуға дейін'), unit: tr('Одна принятая индивидуальная заявка.', 'Бір қабылданған жеке өтінім.'), population: tr('Заявки, принятые в окне отчёта; дальнейшие этапы относятся только к явно связанным записям.', 'Есеп аралығында қабылданған өтінімдер; кейінгі кезеңдер тек нақты байланыстырылған жазбаларға қатысты.'), value: props.report.b2c },
  { id: 'b2b', title: tr('От предложения организации к результату', 'Ұйымға ұсыныстан нәтижеге дейін'), unit: tr('Одно зарегистрированное отправленное предложение.', 'Бір тіркелген жіберілген ұсыныс.'), population: tr('Предложения, зарегистрированные в окне отчёта. Назначения учитываются по явно указанным связям этого предложения, а не по всей организации.', 'Есеп аралығында тіркелген ұсыныстар. Тағайындаулар бүкіл ұйым бойынша емес, осы ұсыныстың нақты байланыстары бойынша есептеледі.'), value: props.report.proposals },
]);
const metricTitles = computed<Record<SalesMetric['id'], string>>(() => ({ authStarted: tr('Пути с начатой авторизацией', 'Авторизациясы басталған жолдар'), authConfirmed: tr('Пути с подтверждённым входом', 'Кіруі расталған жолдар'), authUnconfirmed: tr('Вход начат, подтверждения пока нет', 'Кіру басталды, әзірге растау жоқ'), selectionStarted: tr('Пути с начатым подбором', 'Таңдау басталған жолдар'), selectionMatched: tr('Пути с найденным опубликованным вариантом', 'Жарияланған нұсқа табылған жолдар'), selectionUnmatched: tr('Пути без подходящего опубликованного варианта при проверке', 'Тексеру кезінде сәйкес жарияланған нұсқасы болмаған жолдар'), crmPending: tr('Заявки без подтверждённой доставки CRM', 'CRM жеткізуі расталмаған өтінімдер'), crmDeliveryLagSeconds: tr('Среднее время до подтверждения доставки CRM', 'CRM жеткізуін растауға дейінгі орташа уақыт'), invoicePending: tr('Счета без подтверждённого исполнения', 'Орындалуы расталмаған шоттар'), unstartedAssignments: tr('Назначения с доступом без начала обучения', 'Қолжетімділігі бар, оқу басталмаған тағайындаулар'), credentialPending: tr('Документы в подготовке', 'Дайындалып жатқан құжаттар'), credentialIssuanceSeconds: tr('Среднее время подготовки выданного документа', 'Берілген құжатты дайындаудың орташа уақыты'), unpublishedVersions: tr('Неопубликованные версии программ', 'Бағдарламалардың жарияланбаған нұсқалары'), programsWithoutPublication: tr('Направления без опубликованной программы', 'Жарияланған бағдарламасы жоқ бағыттар'), apiErrors: tr('Технические ошибки API', 'API техникалық қателері'), authErrors: tr('Технические ошибки авторизации', 'Авторизацияның техникалық қателері'), autosaveFailures: tr('Ошибки автосохранения', 'Автосақтау қателері'), checkoutErrors: tr('Ошибки оформления заказа', 'Тапсырысты рәсімдеу қателері'), documentStatusRequests: tr('Запросы о статусе документа', 'Құжат күйі туралы сұраулар'), staleMaterials: tr('Материалы с истёкшим сроком проверки', 'Тексеру мерзімі өткен материалдар') }));
const unavailableTitles = computed(() => ({ external_search_queries: tr('Поисковые запросы и органические позиции', 'Іздеу сұраулары мен органикалық орындар'), cpa: tr('Стоимость привлечения заявки', 'Өтінім тарту құны'), market_share: tr('Доля рынка', 'Нарық үлесі'), auth_drop: tr('Прерывание авторизации', 'Авторизацияның үзілуі'), selection_without_suitable_program: tr('Подбор без подходящей программы', 'Сәйкес бағдарламасыз таңдау') }));
const sourceTitles = computed<Record<JourneyContext['source'], string>>(() => ({ direct: tr('Прямой переход', 'Тікелей өту'), internal: tr('Переход внутри сайта', 'Сайт ішіндегі өту'), search: tr('Поисковый источник', 'Іздеу дереккөзі'), social: tr('Социальная сеть', 'Әлеуметтік желі'), email: tr('Почтовый источник', 'Пошта дереккөзі'), other: tr('Другой источник', 'Басқа дереккөз') }));
const routeTitles = computed<Record<JourneyContext['routeId'], string>>(() => ({ selection: tr('Подбор программы', 'Бағдарлама таңдау'), auth_login: tr('Вход в аккаунт', 'Аккаунтқа кіру'), auth_signup: tr('Создание аккаунта', 'Аккаунт ашу'), home: tr('Главная страница', 'Басты бет'), catalog: tr('Каталог', 'Каталог'), program: tr('Направление', 'Бағыт'), city: tr('Страница города', 'Қала беті'), city_program: tr('Направление в городе', 'Қаладағы бағыт'), contacts: tr('Контакты', 'Байланыс'), b2b: tr('Обучение организации', 'Ұйымды оқыту') }));
const sourceTitle = (value: string) => sourceTitles.value[value as JourneyContext['source']] || tr('Источник не указан', 'Дереккөз көрсетілмеген');
const routeTitle = (value: string) => routeTitles.value[value as JourneyContext['routeId']] || tr('Маршрут не указан', 'Бағыт көрсетілмеген');
const scope = (value: SalesMetric['scope']) => value === 'journey_cohort' ? tr('Действующие пути с согласием из окна отчёта', 'Есеп аралығындағы келісімі бар қолданыстағы жолдар') : value === 'current_inventory' ? tr('Текущее состояние записей', 'Жазбалардың ағымдағы күйі') : value === 'utc_days' ? tr('Суточные счётчики UTC в окне', 'Аралықтағы UTC тәуліктік есептегіштері') : tr('Записи, созданные в окне', 'Аралықта құрылған жазбалар');
const percent = (value: number | null) => value === null ? tr('Нет знаменателя', 'Бөлім жоқ') : new Intl.NumberFormat(locale.value === 'kk' ? 'kk-KZ' : 'ru-KZ', { style: 'percent', maximumFractionDigits: 1 }).format(value);
const utc = (value: string) => new Intl.DateTimeFormat(locale.value === 'kk' ? 'kk-KZ' : 'ru-KZ', { timeZone: 'UTC', dateStyle: 'short', timeStyle: 'medium' }).format(new Date(value));
</script>
<template>
  <section class="space-y-5" :aria-label="tr('Этапы заявок и обучения', 'Өтінімдер мен оқу кезеңдері')">
    <div class="lms-card space-y-4">
      <h2 class="text-2xl font-bold">{{ tr('Этапы заявок и обучения', 'Өтінімдер мен оқу кезеңдері') }}</h2>
      <p class="text-sm">{{ tr('Окно включения в группу:', 'Топқа қосу аралығы:') }} <time :datetime="report.window.from">{{ utc(report.window.from) }}</time> — <time :datetime="report.window.until">{{ utc(report.window.until) }}</time> {{ tr('(начало включено, конец исключён), UTC.', '(басталуы кіреді, аяқталуы кірмейді), UTC.') }} {{ tr('Текущее состояние на:', 'Ағымдағы күй уақыты:') }} <time :datetime="report.asOf">{{ utc(report.asOf) }}</time> UTC.</p>
      <p class="lms-note">{{ tr('У трёх разделов разные единицы и группы. Их суммы нельзя складывать или делить друг на друга. Повторная связь не создаёт дополнительную заявку. Дальнейшие учебные этапы проверяются по последовательным фактам одного связанного назначения; отказ на экзамене не считается технической ошибкой.', 'Үш бөлімнің бірліктері мен топтары әртүрлі. Олардың қосындыларын қосуға немесе бір-біріне бөлуге болмайды. Қайталама байланыс қосымша өтінім жасамайды. Кейінгі оқу кезеңдері бір байланысты тағайындаудың дәйекті деректері бойынша тексеріледі; емтиханнан өтпеу техникалық қате болып саналмайды.') }}</p>
      <p class="text-sm text-slate-600">{{ tr('Данные могут включать тестовые действия текущего окружения. Полная конверсия всех посетителей и причинное влияние рекламы здесь не измеряются.', 'Деректер осы ортаның сынақ әрекеттерін қамтуы мүмкін. Барлық келушілердің толық конверсиясы және жарнаманың себептік әсері мұнда өлшенбейді.') }}</p>
      <NuxtLink class="lms-button secondary" :to="path('/admin/leads')">{{ tr('Рассмотреть заявки и связи', 'Өтінімдер мен байланыстарды қарау') }}</NuxtLink>
    </div>
    <article v-for="funnel in funnels" :key="funnel.id" class="lms-card min-w-0 space-y-4" :aria-label="funnel.title">
      <h3 class="text-xl font-semibold">{{ funnel.title }}</h3><p class="font-medium">{{ tr('Единица:', 'Бірлік:') }} {{ funnel.unit }}</p><p class="text-sm text-slate-600">{{ funnel.population }}</p>
      <p class="text-sm">{{ tr('Для каждого этапа знаменатель — число записей предыдущего этапа; для первого — размер исходной группы. Доли рассчитаны сервером по одной группе, а не по суммам событий.', 'Әр кезеңнің бөлімі — алдыңғы кезеңдегі жазбалар саны; бірінші кезең үшін — бастапқы топ көлемі. Үлестер оқиғалар қосындысы бойынша емес, бір топ бойынша серверде есептелген.') }}</p>
      <p class="font-medium">{{ tr('Размер исходной группы:', 'Бастапқы топ көлемі:') }} {{ funnel.value.cohortSize }}</p>
      <p v-if="funnel.value.cohortSize === 0 && !funnel.value.truncated" class="lms-note" role="status">{{ tr('В этом окне нет записей выбранной группы.', 'Осы аралықта таңдалған топтың жазбалары жоқ.') }}</p>
      <p v-if="funnel.value.truncated" class="lms-error" role="alert">{{ tr('Группа превышает предел отчёта. Показанные значения неполные; сузьте период перед сравнением.', 'Топ есеп шегінен асады. Көрсетілген мәндер толық емес; салыстырмас бұрын кезеңді қысқартыңыз.') }} {{ tr('Предел:', 'Шек:') }} {{ funnel.value.limit }}</p>
      <p v-if="funnel.value.invalidLinks" class="lms-note">{{ tr('Связи, требующие проверки:', 'Тексеруді қажет ететін байланыстар:') }} {{ funnel.value.invalidLinks }}</p>
      <ol class="space-y-3"><li v-for="stage in funnel.value.stages" :key="stage.id" class="rounded-lg border p-4 space-y-2"><p class="font-semibold">{{ titles[stage.id] }}</p><div class="flex flex-wrap justify-between gap-3 text-sm"><span>{{ tr('Записей:', 'Жазбалар:') }} <strong class="tabular-nums">{{ stage.count }}</strong></span><span>{{ tr('Знаменатель:', 'Бөлім:') }} <strong class="tabular-nums">{{ stage.denominator }}</strong></span><span>{{ tr('Доля:', 'Үлес:') }} <strong class="tabular-nums">{{ percent(stage.rate) }}</strong></span></div></li></ol>
    </article>
    <section class="lms-card space-y-4" :aria-label="tr('Операционные показатели', 'Операциялық көрсеткіштер')">
      <h3 class="text-xl font-semibold">{{ tr('Операционные показатели', 'Операциялық көрсеткіштер') }}</h3>
      <p class="text-sm text-slate-600">{{ tr('Начатый вход без серверного подтверждения означает только отсутствие подтверждения на момент отчёта, а не доказанный уход. Один путь может содержать и успешный, и безрезультатный подбор после изменения параметров; эти счётчики не являются взаимоисключающими. Для исходов размер выборки — число путей с началом соответствующего действия.', 'Сервер растауы жоқ басталған кіру тек есеп кезінде растаудың жоқтығын білдіреді, дәлелденген кетуді емес. Параметрлер өзгергеннен кейін бір жолда сәтті де, нәтижесіз де таңдау болуы мүмкін; бұл есептегіштер бірін-бірі жоққа шығармайды. Нәтижелер үшін іріктеме көлемі — тиісті әрекет басталған жолдар саны.') }}</p>
      <div class="grid gap-4 sm:grid-cols-2"><article v-for="metric in report.metrics" :key="metric.id" class="rounded-lg border p-4 space-y-2"><h4 class="font-semibold">{{ metricTitles[metric.id] }}</h4><p class="text-lg font-bold tabular-nums">{{ metric.value === null ? tr('Не измеряется', 'Өлшенбейді') : metric.value }}<span v-if="metric.value !== null" class="text-sm font-normal"> {{ metric.unit === 'seconds' ? tr('секунд', 'секунд') : tr('записей', 'жазба') }}</span></p><p class="text-sm">{{ scope(metric.scope) }} · {{ tr('Размер выборки:', 'Іріктеме көлемі:') }} {{ metric.sampleSize }}</p><p v-if="metric.unavailableReason" class="text-sm text-slate-600">{{ tr('Для достоверного расчёта недостаточно предусмотренных данных или правил измерения.', 'Сенімді есептеу үшін көзделген деректер немесе өлшеу ережелері жеткіліксіз.') }}</p></article></div>
    </section>
    <section class="lms-card space-y-4" :aria-label="tr('Источники квалифицированных заявок', 'Іріктелген өтінімдердің дереккөздері')"><h3 class="text-xl font-semibold">{{ tr('Источники квалифицированных заявок', 'Іріктелген өтінімдердің дереккөздері') }}</h3><p class="text-sm">{{ tr('Первый сохранённый источник квалифицированных заявок в группе действующих путей с согласием. Отсутствие данных не означает прямой или органический переход.', 'Келісім берілген қолданыстағы жолдар тобындағы іріктелген өтінімдердің бірінші сақталған дереккөзі. Деректердің болмауы тікелей немесе органикалық өтуді білдірмейді.') }}</p><p v-if="!report.qualifiedSources.length" role="status">{{ tr('Для выбранной группы источники не записаны.', 'Таңдалған топ үшін дереккөздер жазылмаған.') }}</p><ul class="space-y-3"><li v-for="row in report.qualifiedSources" :key="row.routeId + ':' + row.city + ':' + row.source" class="rounded-lg border p-3"><p class="break-words">{{ routeTitle(row.routeId) }} · {{ leadCityLabel(row.city, locale) || tr('Город не указан', 'Қала көрсетілмеген') }} · {{ sourceTitle(row.source) }}</p><p>{{ tr('Квалифицированных заявок:', 'Іріктелген өтінімдер:') }} <strong>{{ row.qualifiedLeads }}</strong></p></li></ul></section>
    <section class="lms-card space-y-3"><h3 class="text-xl font-semibold">{{ tr('Показатели без достоверного измерения', 'Сенімді өлшемі жоқ көрсеткіштер') }}</h3><ul class="list-disc pl-5 space-y-2"><li v-for="item in report.unavailable" :key="item">{{ unavailableTitles[item] }}</li></ul><p class="text-sm text-slate-600">{{ tr('Для этих показателей не подставляются нули, приблизительные проценты или внешние сведения без подключённого источника.', 'Бұл көрсеткіштерге қосылған дереккөзсіз нөлдер, шамамен пайыздар немесе сыртқы мәліметтер қойылмайды.') }}</p></section>
  </section>
</template>
